In [5]:
# 3. Find the shape, size and dimension of the following array?

import numpy as np

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])


In [11]:
a.shape

(3, 4)

In [12]:
a.size

12

In [13]:
a.ndim

2

In [15]:
# 4. Write python code to access the first row of the following array?
a[0]

array([1, 2, 3, 4])

In [22]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
a[2 , 3]

12

In [25]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
odd_indexed_elements = arr[:, 1::2]

print(odd_indexed_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [24]:
#7. Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print(random_matrix)


[[0.75315431 0.48569682 0.05472746]
 [0.26544724 0.28042382 0.20763394]
 [0.01607964 0.85613671 0.11703469]]


In [26]:
# 9. Write code to increase the dimension of the following array?
new_arr = np.expand_dims(arr, axis=0)

print("Original array:")
print(arr)
print("New array with increased dimension:")
print(new_arr)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array with increased dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [27]:
# 10. How to transpose the following array in NumPy?
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [28]:
# 11. Consider the following matrix:

In [40]:
arr1 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

In [41]:
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [42]:
arr1 - arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
arr2 / arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
result = np.matmul(arr1, arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [46]:
arr1.shape

(3, 4)

In [47]:
arr2.shape

(3, 4)

In [48]:
arr1 * arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])